on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:
  hello_world_job:
    runs-on: windows-latest
    name: Build and Analyse
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm install
      - name: install ESLint
        run: npm install eslint babel-eslint --save-dev
      - name: Run ESLint
        run: .\node_modules\.bin\eslint --no-eslintrc --format json entry --output-file result.json
        continue-on-error: true
      - id: main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          LANG: JS
        uses: applibgroup/HarmonyOs-build@v2.8
      
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with: 
          name: artifact
          path: ${{ github.workspace }}\result.json
