on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:
  hello_world_job:
    runs-on: windows-latest
    continue-on-error: true
    name: Build and Analyse
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - id: main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          LANG: JS
        uses: applibgroup/HarmonyOs-build@v4.0
      
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with: 
          name: artifact
          path: ${{ github.workspace }}\result.json
